# Generated by Django 5.1 on 2024-09-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='std',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Roll_No', models.IntegerField()),
                ('Department', models.TextField()),
                ('session', models.TextField()),
            ],
        ),
    ]
